#!/bin/bash

if ! [[ -d $HOME/.config ]]; then
    mkdir $HOME/.config
fi
if ! [[ -f $HOME/.config/system-logger.conf ]]; then
    echo "time_interval=60" > $HOME/.config/system-logger.conf
    echo "log_dir=$HOME/.cache/system-logger" >> $HOME/.config/system-logger.conf
fi
time_interval=60
log_dir=""
while read line; do
    if [[ $line =~ ^time_interval=([0-9]+) ]]; then
        time_interval=${BASH_REMATCH[1]}
    elif [[ $line =~ ^log_dir=(.+) ]]; then
        log_dir=${BASH_REMATCH[1]}
    fi
done < $HOME/.config/system-logger.conf
if ! [[ -f $log_dir ]]; then
    mkdir -p -v "$log_dir"
fi
cpu_cores=$(grep -c ^processor /proc/cpuinfo)
IFS='\n'
disks_str=$(awk '$3 !~ /ram|loop|sr0|dm-0/ {print $3}' /proc/diskstats | grep -oE [a-z]+ | sort -u)
IFS=$'\n' read -rd '' -a disks <<< "$disks_str"
internet_interface=$(ip route show | awk '/default/ {print $5}')
while true; do
    today=$(date +"%Y-%m-%d")
    while true; do
        row=""
        if ! [[ -f $log_dir/$today.csv ]]; then
            header="timestamp,"
            for ((i=0; i<$cpu_cores; i++)); do
                header="$header"cpu"$i,"
            done
            IFS=' '
            header="$header"intr,ctxt,btime,processes,procs_running,procs_blocker,softirq,MemFree,SwapFree,
            for disk in "${disks[@]}"; do
                header=$header"$disk"_free,"$disk"_read,"$disk"_write,
            done
            header=$header"$internet_interface"_received,"$internet_interface"_transmitted
            echo $header > $log_dir/$today.csv
        fi
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        IFS=' '
        date=$(echo $timestamp | grep -Po ".*(?= )")
        if ! [[ $date == $today ]]; then
            zip -m $log_dir/$today $log_dir/$today.csv
            break
        fi
        stat=$(cat /proc/stat)
        meminfo=$(cat /proc/meminfo)
        mounts=$(cat /proc/mounts)
        net_dev=$(cat /proc/net/dev)
        row=$timestamp
        cpu_stat=$(echo "$stat" | grep "^cpu[0-9]" | sed 's/cpu[0-9]\+ //g')
        IFS=$'\n' read -rd '' -a cpu_data <<< "$cpu_stat"
        for core_data in "${cpu_data[@]}"; do
            IFS=' '
            read -a core_times <<< $core_data
            core_full_time=0
            for core_time in "${core_times[@]}"; do
                core_full_time=$((core_full_time + core_time))
            done
            core_id=$(echo $core_data | awk '{print $4}')
            core_usage=$((100000 * core_id))
            core_usage=$((core_usage / core_full_time))
            core_usage=$((100000 - core_usage))
            row=$row,$core_usage
        done
        row=$row,$(echo $stat | awk '$1 ~ /intr|ctxt|btime|processes|procs_running|procs_blocked|softirq/ {print $2}' | tr '\n' ',')
        row=$row$(echo $meminfo | awk '$1 ~ /MemFree:|SwapFree/ {print $2}' | tr '\n', ',')
        for disk in "${disks[@]}"; do
            sector_size=$(cat /sys/class/block/$disk/queue/hw_sector_size)
            disk_size=$(cat /sys/class/block/$disk/size)
            free_space=$(($disk_size * $sector_size)) 
            read=$(cat /proc/diskstats | awk "\$3 == \"$disk\" {print \$6}")
            write=$(cat /proc/diskstats | awk "\$3 == \"$disk\" {print \$10}")
            row=$row$free_space,$read,$write,
        done
        row=$row$(grep "$internet_interface" /proc/net/dev | awk '{print $2}'),$(grep "$internet_interface" /proc/net/dev | awk '{print $10}')
        echo $row >> $log_dir/$today.csv
        sleep $time_interval
    done
done